# Generated by Django 4.0.6 on 2023-01-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
